name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: testDebugUnitTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
        with:
          arguments: ${{ matrix.target }}
